services:
  - type: web
    name: linker-backend
    env: node
    region: singapore
    plan: free
    buildCommand: cd apps/server && npm install --legacy-peer-deps && npx prisma generate && npm run build
    startCommand: cd apps/server && npm run start:prod
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_ACCESS_EXPIRES
        value: 15m
      - key: JWT_REFRESH_EXPIRES
        value: 7d
      - key: PORT
        value: 4000
      - key: CORS_ORIGIN
        sync: false
