services:
  - type: web
    name: LINKER
    env: node
    plan: free

    rootDir: apps/server

    buildCommand: "npm install && npx prisma generate --schema=prisma/schema.prisma && npx prisma migrate deploy --schema=prisma/schema.prisma && npm run build"

    startCommand: "npm run start:prod"

    envVars:
      - key: PORT
        value: 10000

      - key: DATABASE_URL
        sync: false

      - key: JWT_ACCESS_SECRET
        sync: false

      - key: JWT_REFRESH_SECRET
        sync: false

      - key: JWT_ACCESS_EXPIRES
        value: '15m'

      - key: JWT_REFRESH_EXPIRES
        value: '7d'

      - key: SUPABASE_URL
        sync: false

      - key: SUPABASE_PUBLIC_ANON_KEY
        sync: false

      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false

      - key: CORS_ORIGIN
        sync: false
