services:
  - type: web
    name: linker-api
    env: node
    rootDir: .
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm run start:prod
    postDeployCommand: npx prisma migrate deploy
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: JWT_ACCESS_EXPIRES
        value: 15m
      - key: JWT_REFRESH_EXPIRES
        value: 7d
      - key: PORT
        value: 4000
      - key: DIRECT_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
